FROM openjdk:11-slim

# Set environment variables
ENV SPARK_VERSION=3.3.2
ENV HADOOP_VERSION=3
ENV HADOOP_AWS_VERSION=3.3.1
ENV AWS_SDK_VERSION=1.12.406  
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV SPARK_HOME=/opt/spark
ENV PATH=$SPARK_HOME/bin:$JAVA_HOME/bin:$PATH
ENV PYSPARK_PYTHON=python3
ENV HOME=/root
ENV SPARK_LOCAL_IP=127.0.0.1

# Install Python, pip, and required system packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 python3-pip wget ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Symlink python and pip
RUN ln -s /usr/bin/python3 /usr/bin/python && \
    ln -s /usr/bin/pip3 /usr/bin/pip

# Verify installations
RUN java -version && python --version && pip --version

# Download and install Spark
RUN wget -q https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
    tar -xzf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
    mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} $SPARK_HOME && \
    rm spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz

# Add required Hadoop AWS & AWS SDK JARs
RUN wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar -P $SPARK_HOME/jars/ && \
    wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/${AWS_SDK_VERSION}/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar -P $SPARK_HOME/jars/

# Install Python dependencies
COPY scripts/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Set working directory
WORKDIR /app

# Copy PySpark scripts
COPY scripts/validation.py .
COPY scripts/helperfunction.py .

# Default command
CMD ["python", "validation.py"]
