FROM bitnami/spark:latest

WORKDIR /app

# Install Python dependencies
COPY scripts/requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy your scripts into the container
COPY scripts/transformation.py .
COPY scripts/validation.py .
COPY scripts/helperfunction.py .

# Default entrypoint (can be overridden in ECS task definition)
ENTRYPOINT ["spark-submit", "transformation.py"]
