name: Deploy Lambda

on:
  push:
    paths:
      - 'lambda/**'
      - '.github/workflows/deploy-lambda.yml'
    branches: [ main ]

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and package lambda
        working-directory: lambda
        run: |
          mkdir -p package
          cp lambda_s3_validation.py package/
          cd package
          zip -r ../lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name lambda-s3-validator \
            --zip-file fileb://lambda/lambda.zip
